name: norminette

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
      - name: Norminette
